/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lojainformatica;

import javax.swing.JOptionPane;

/**
 *
 * @author oaugu
 */
public class AdicionarDados extends javax.swing.JFrame {
      
    Computador objAlterar = null;
    
    
    
    /**
     * Creates new form ConsultarDados
     */
    public AdicionarDados() {
        initComponents();
    }
    
    public AdicionarDados(Computador obj) {
        initComponents();
        
        this.objAlterar = obj;
        lblID.setText(String.valueOf(objAlterar.getID()));
        txtHD.setText(String.valueOf(objAlterar.getHD()));
        txtProcessador.setText(String.valueOf(objAlterar.getProcessador()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInputHD = new javax.swing.JLabel();
        txtHD = new javax.swing.JTextField();
        txtInputCPU = new javax.swing.JLabel();
        btnSalvarPecas = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();
        txtProcessador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInputHD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtInputHD.setText("HD:");

        txtInputCPU.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txtInputCPU.setText("PROCESSADOR:");

        btnSalvarPecas.setText("Salvar");
        btnSalvarPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPecasActionPerformed(evt);
            }
        });

        txtTitle.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        txtTitle.setText("Loja Informatica");

        txtProcessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcessadorActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        lblID.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInputCPU)
                    .addComponent(txtInputHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHD, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(txtProcessador, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(btnSalvarPecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblID)
                .addGap(52, 52, 52)
                .addComponent(txtTitle)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputHD)
                    .addComponent(txtHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputCPU)
                    .addComponent(txtProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvarPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPecasActionPerformed
      if(objAlterar == null){
          String HD = txtHD.getText();
      String processador = txtProcessador.getText();
      
      Computador novoComputador = new Computador(HD,processador);

      boolean retorno = ComputadorDAO.salvar(novoComputador);
      
            if(retorno == true){
                JOptionPane.showMessageDialog(rootPane, "Sucesso - id: " + novoComputador.getID());
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha!");
            }
      }else{             
                String HD = txtHD.getText();
                String processador = txtProcessador.getText();
                
                objAlterar.setHD(HD);
                objAlterar.setProcessador(processador);
                
                boolean retorno = ComputadorDAO.alterar(objAlterar);
                
                if(retorno){
                    JOptionPane.showMessageDialog(rootPane, "Sucesso");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Falha");
                }
                
                
      }  
    }//GEN-LAST:event_btnSalvarPecasActionPerformed

    private void txtProcessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcessadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcessadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdicionarDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarPecas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtHD;
    private javax.swing.JLabel txtInputCPU;
    private javax.swing.JLabel txtInputHD;
    private javax.swing.JTextField txtProcessador;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
